# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-appserver/Dockerfile'
        repository: 'yelb-appserver'
        tags: |
          $(tag)

    - task: prisma-cloud-compute-scan@3
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-cloud-demo'
        artifact: 'yelb-appserver:$(tag)'
        project: 'Cyberweek Project'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-ui/Dockerfile'
        tags: |
          $(tag)

    - task: prisma-cloud-compute-scan@3
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-cloud-demo'
        artifact: 'yelb-ui:$(tag)'
        project: 'Cyberweek Project'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/yelb-db/Dockerfile'
        tags: |
          $(tag)
    - task: prisma-cloud-compute-scan@3
      inputs:
        scanType: 'images'
        twistlockService: 'prisma-cloud-demo'
        artifact: 'yelb-db:$(tag)'
        project: 'Cyberweek Project'
